<?php

/**
 * Respond to a parsed message failing authentification.
 *
 * @param array $message
 *   The mail message Feeds was trying to parse.
 */
function mailauthfail_mailhandler_auth_failed($message) {
  global $base_url;
  $link = $base_url;
  // Send mail on fail
  mailauthfail_drupal_mail('default_from', get_toaddress($message), 'Ukendt bruger ved Digital Formidling', 'Hej<br><br>Du er ikke oprettet som bruger ved <a href=' . $link . '>' . $link . '</a><br>');
}

/**
 * Return the "to address" from the headers. Note: will not return "toad dress".
 *
 * @param $message
 *   the message retrieved by Mailhandler
 */
 function get_toaddress($message) {
    $toaddress = '';
    if (isset($message['header'])) {
      $header = $message['header'];
      if (isset($header->fromaddress)) {
        $toaddress = $header->fromaddress;
      }
    }
    preg_match('/\<(.+?\@.+?)\>/', $toaddress, $matches);
    if (isset($matches[1])) {
      $toaddress = $matches[1];
    }
    return strtolower($toaddress);
  }

/**
 * Simple wrapper function for drupal_mail() to avoid extraneous code.
 */
function mailauthfail_drupal_mail($from = 'default_from', $to, $subject, $message) {
  $my_module = 'mailhandler';
  $my_mail_token = microtime();
  if ($from == 'default_from') {
    // Change this to your own default 'from' email address.
    $from = variable_get('site_mail', 'My Email Address <it-udvikling@fynbib.dk>');
  }
  $message = array(
    'id' => $my_module . '_' . $my_mail_token,
    'to' => $to,
    'subject' => $subject,
    'body' => array($message),
    'headers' => array(
      'From' => $from,
      'Sender' => $from,
      'Return-Path' => $from,
      'Content-Type' => 'text/html; charset=UTF-8; format=flowed',
    ),
  );
  $system = drupal_mail_system($my_module, $my_mail_token);
  $message = $system->format($message);
  if ($system->mail($message)) {
    return TRUE;
  }
  else {
    return FALSE;
  }
}